[project]
name = "igcview"
version = "0.1.0"
description = "Lists details of IGC files and does file format conversion"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "libigc>=1.1.0",
    "tabulate>=0.9.0",
]
